# Generated by Django 4.1.7 on 2023-04-18 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
