# Generated by Django 4.1.7 on 2023-03-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_contacts_publishedmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='speciality',
            field=models.CharField(default='----', max_length=100),
        ),
    ]
