# Generated by Django 4.1.7 on 2023-03-24 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_contacts_speciality'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublishedManager',
        ),
    ]
